### PR TITLE
Change group not to produce a Union when the document cannot be flattened

### LINKED ISSUE #99: changesUponFlattening can be slow
In https://github.com/dhall-lang/dhall-haskell/issues/1496#issuecomment-549003609 Gabriel describes a case where rendering a type error takes multiple seconds.

You can reproduce the issue with the following command, after adding a type error, for example by removing the `Some` on [this line](https://github.com/Gabriel439/dhall-kubernetes-charts/blob/33eb92e4d55224bb103c19b1fb4e56e16060b3d1/stable/jenkins/index.dhall#L97).

```
$ dhall type --file stable/jenkins/index.dhall --explain
```

These are the top cost centers:

```
COST CENTRE               MODULE                                SRC                                                            %time %alloc

getDecodeAction           Codec.CBOR.Decoding                   src/Codec/CBOR/Decoding.hs:311:1-55                             27.1   34.8
changesUponFlattening     Data.Text.Prettyprint.Doc.Internal    src/Data/Text/Prettyprint/Doc/Internal.hs:(553,1)-(591,21)      19.3   22.6
prettyCharacterSet        Dhall.Pretty.Internal                 src/Dhall/Pretty/Internal.hs:(502,1)-(1139,62)                   6.5    5.1
renderLazy                Data.Text.Prettyprint.Doc.Render.Text src/Data/Text/Prettyprint/Doc/Render/Text.hs:59:1-92             6.5    6.1
deserialiseIncremental    Codec.CBOR.Read                       src/Codec/CBOR/Read.hs:(165,1)-(167,46)                          4.7    3.5
```

Note that `changesUponFlattening` takes nearly 20% of the time!

So I had a closer look at this function and noticed this case:

https://github.com/quchen/prettyprinter/blob/7da3b1d32f8a74efb3bcf1b2d062f8f24a64c918/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L556

`Union` is introduced by `group` which `dhall` apparently uses a _lot_: the same profile contains over 600000 entries for `group`!

https://github.com/quchen/prettyprinter/blob/7da3b1d32f8a74efb3bcf1b2d062f8f24a64c918/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L526-L530

So I wondered: If `changesUponFlattening` is only used by `group`, and the `Union` constructor is also only introduced by `group`, why does `changesUponFlattening` have to scrutinize it at all? So I tried this change:

```diff
-    Union x _       -> changesUponFlattening x <|> Just x
+    Union x _       -> Just x
```

This shaves about 18% off the total time when profiling and about 42% when using the unprofiled executable (and I'm not sure where that difference comes from)!

Unfortunately it also breaks the fusion property tests, which now fail with the classic

> »SFail« must not appear in a rendered »SimpleDocStream«. This is a bug in the layout algorithm! Please report this as a bug

I haven't figured out yet quite _how_ it breaks `fuse` though!

### LINKED ISSUE #112: Make group Fail faster
I noticed that in many `Union`s, the `Fail` is somewhat hidden. E.g.

```haskell
> diag $ group $ "x" <> hardline
Union 
    ( Cat ( Char 'x' ) Fail ) 
    ( Cat ( Char 'x' ) Line )
```

To detect that the first alternative fails, the layout algorithm has to traverse everything that comes before the `Fail`.

I wonder whether `group` could simply produce this instead:

```haskell
> diag $ group $ "x" <> hardline
Union 
    Fail
    ( Cat ( Char 'x' ) Line )
```

This could save a lot of work for the layouters!

Is there any reason why `group` shouldn't do this?

(#99 is somewhat related)

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #99, fixes #112.

### CODE REVIEW

**Comment by sjakobi** [comment]
Previously:

```haskell
> diag $ group $ "x" <> hardline
Union 
    ( Cat ( Char 'x' ) Fail ) 
    ( Cat ( Char 'x' ) Line )
```

Now:

```haskell
Cat ( Char 'x' ) Line
```

**Comment by sjakobi** [comment]
`dhall`'s `tasty` testsuite still passes when built with this branch.

**Comment by sjakobi** [comment]
It seems that we'd no longer produce `Fail`s at all! We might as well remove the constructor then?!

**Comment by sjakobi** [comment]
> It seems that we'd no longer produce `Fail`s at all!

Nope. `flatten` still returns `Fail` for `Line`. Maybe we can get rid of that though…

**Comment by sjakobi** [comment]
> `flatten` still returns `Fail` for `Line`. Maybe we can get rid of that though…

If `flatten` would also produce a `FlattenResult`, I think that probably reduce laziness, probably in a bad way?!

**Comment by sjakobi** [comment]
> If `flatten` would also produce a `FlattenResult`, I think that probably reduce laziness, probably in a bad way?!

At least `layoutCompact`, which doesn't care about a first `Union` alternative at all, would suffer

https://github.com/quchen/prettyprinter/blob/ff555e19b7b17a74f16e6fb062256a57dabe4d92/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1858

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 1]
```diff
@@ -540,35 +541,47 @@ group x = case changesUponFlattening x of
...
+
 -- | Choose the first element of each @Union@, and discard the first field of
 -- all @FlatAlt@s.
 --
 -- The result is 'Just' if the element might change depending on the layout
 -- algorithm (i.e. contains differently renderable sub-documents), and 'Nothing'
 -- if the document is static (e.g. contains only a plain 'Empty' node). See
 -- [Group: special flattening] for further explanations.
-changesUponFlattening :: Doc ann -> Maybe (Doc ann)
+changesUponFlattening :: Doc ann -> FlattenResult (Doc ann)
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Maybe this would be a better name:

```suggestion
tryFlatten :: Doc ann -> FlattenResult (Doc ann)
```

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 2]
```diff
@@ -540,35 +541,55 @@ group x = case changesUponFlattening x of
...
+-- contains a hard 'Line' or 'Fail'.
+-- See [Group: special flattening] for further explanations.
+changesUponFlattening :: Doc ann -> FlattenResult (Doc ann)
 changesUponFlattening = \doc -> case doc of
-    FlatAlt _ y     -> Just (flatten y)
-    Line            -> Just Fail
-    Union x _       -> changesUponFlattening x <|> Just x
+    FlatAlt _ y     -> Flattened (flatten y)
+    Line            -> NeverFlat
+    Union x _       -> Flattened x
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: This also includes #100 / fixes #99, mostly because I couldn't be bothered to write an `Alternative` instance.

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 3]
```diff
@@ -540,35 +541,52 @@ group x = case changesUponFlattening x of
 -- See https://github.com/quchen/prettyprinter/issues/22 for the  corresponding
 -- ticket.
 
+data FlattenResult a
+    = Flattened a
+    -- ^ a is likely flatter than the input.
+    | AlreadyFlat
+    -- ^ The input was already flat, e.g. a 'Text'.
+    | NeverFlat
+    -- ^ The input couldn't be flattened: It contained a 'Line' or 'Fail'.
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: The main idea of this PR is to represent the old `Nothing` result with _two_ constructors: One to indicate that the result is already flat enough, the other to indicate that flattening is impossible, and which allows shortcuts.

**Comment by sjakobi** [comment]
This speeds up the case described in https://github.com/dhall-lang/dhall-haskell/issues/1496#issuecomment-549003609 from ~11.9s to ~9.2s for me.

I'm pretty confident that this is a good change at this stage.

**Comment by sjakobi** [comment]
This would also fix the issue of repeated `group`s I mentioned in https://github.com/quchen/prettyprinter/pull/100#issuecomment-576057555.

**Comment by sjakobi** [comment]
I wonder whether I should add some kind of test for this. This patch should be unobservable after rendering, so I guess I could use `diag`…

**Comment by sjakobi** [comment]
> This would also fix the issue of repeated `group`s I mentioned in [#100 (comment)](https://github.com/quchen/prettyprinter/pull/100#issuecomment-576057555).

Oops, nope:

```haskell
> diag $ group . group . group $ "x" <> line
Union 
    ( Cat ( Char 'x' ) ( Char ' ' ) ) 
    ( Union 
        ( Cat ( Char 'x' ) ( Char ' ' ) ) 
        ( Union 
            ( Cat ( Char 'x' ) ( Char ' ' ) ) 
            ( Cat ( Char 'x' ) 
                ( FlatAlt Line ( Char ' ' ) )
            )
        )
    )
```

**Comment by sjakobi** [comment]
> This speeds up the case described in [dhall-lang/dhall-haskell#1496 (comment)](https://github.com/dhall-lang/dhall-haskell/issues/1496#issuecomment-549003609) from ~11.9s to ~9.2s for me.

And here's the corresponding profile (see https://github.com/quchen/prettyprinter/issues/99#issue-524740377 for the original):

```
	Wed Jan 22 15:15 2020 Time and Allocation Profiling Report  (Final)

	   dhall +RTS -p -RTS type --file /home/simon/src/dhall-kubernetes-charts/stable/jenkins/index.dhall --explain

	total time  =       14.08 secs   (14079 ticks @ 1000 us, 1 processor)
	total alloc = 36,050,760,208 bytes  (excludes profiling overheads)

COST CENTRE               MODULE                                             SRC                                                                         %time %alloc

getDecodeAction           Codec.CBOR.Decoding                                src/Codec/CBOR/Decoding.hs:311:1-55                                          51.0   65.6
prettyCharacterSet        Dhall.Pretty.Internal                              src/Dhall/Pretty/Internal.hs:(512,1)-(1177,62)                                5.6    3.4
layoutWadlerLeijen        Data.Text.Prettyprint.Doc.Internal                 src/Data/Text/Prettyprint/Doc/Internal.hs:(1775,1)-(1843,60)                  5.5    3.0
unorderedTraverseWithKey_ Dhall.Map                                          src/Dhall/Map.hs:(647,1)-(648,65)                                             5.3    5.1
escapeLabel               Dhall.Pretty.Internal                              src/Dhall/Pretty/Internal.hs:(428,1)-(433,34)                                 4.0    2.1
renderLazy                Data.Text.Prettyprint.Doc.Render.Terminal.Internal src/Data/Text/Prettyprint/Doc/Render/Terminal/Internal.hs:(108,1)-(148,60)    3.7    3.7
removeTrailingWhitespace  Data.Text.Prettyprint.Doc.Internal                 src/Data/Text/Prettyprint/Doc/Internal.hs:(1477,1)-(1537,119)                 2.3    1.1
hashExpression            Dhall.Import                                       src/Dhall/Import.hs:(1133,1)-(1134,67)                                        2.2    2.4
styleToRawText            Data.Text.Prettyprint.Doc.Render.Terminal.Internal src/Data/Text/Prettyprint/Doc/Render/Terminal/Internal.hs:(278,1)-(304,29)    1.8    2.0
deserialiseIncremental    Codec.CBOR.Read                                    src/Codec/CBOR/Read.hs:(165,1)-(167,46)                                       1.7    1.1
layoutSmart               Data.Text.Prettyprint.Doc.Internal                 src/Data/Text/Prettyprint/Doc/Internal.hs:(1741,1)-(1767,59)                  1.6    0.2
changesUponFlattening     Data.Text.Prettyprint.Doc.Internal                 src/Data/Text/Prettyprint/Doc/Internal.hs:(567,1)-(607,21)                    1.5    1.1
csi                       System.Console.ANSI.Codes                          src/System/Console/ANSI/Codes.hs:77:1-75                                      1.4    2.7
toBuilder                 Codec.CBOR.Write                                   src/Codec/CBOR/Write.hs:(84,1)-(85,57)                                        1.0    1.0

```

* time: 1.5% (down from 19.3%)
* allocations: 1.1% (down from 22.6%)
