### PR TITLE
Fix #83 by changing the choice of minNestingLevel

### LINKED ISSUE #83: Inconsistent formatting within align
If you clone https://github.com/sjakobi/dhall-issue1400 and run the following command within `stack repl`, you should see:

```haskell
> putStrLn $ renderString $ layoutSmart defaultLayoutOptions $ prettyE sample
[ [ [ 0
    ]
  , [ 0 ]
  , [ 111111111111111111111111111111111111111111111111111111111111111111111111111
    ]
  ]
]
```

The problem is that the first `[ 0 ]` is incorrectly formatted with a line break, while the second `[ 0 ]` is formatted correctly on a single line. The correct formatting would be this:

```haskell
[ [ [ 0 ]
  , [ 0 ]
  , [ 111111111111111111111111111111111111111111111111111111111111111111111111111
    ]
  ]
]
```

Note that one of the `align`ed elements must exceed the page width to trigger the malformatting of the first element.

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
I'll try to explain this later… ;)

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 1]
```diff
@@ -1785,7 +1785,9 @@ layoutWadlerLeijen
       | fits pWidth minNestingLevel availableWidth x = x
       | otherwise = y
       where
-        minNestingLevel = min lineIndent currentColumn
+        minNestingLevel = case y of
+            SLine _ _ -> lineIndent
+            _         -> currentColumn
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: We check whether the second alternative (`y`) starts with a line break in order to detect hanging layouts as (partially) explained in https://github.com/quchen/prettyprinter/issues/83#issuecomment-546120600.

Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: The loss of laziness in `y` is a bit unfortunate. Since `best` seems to be quite lazy too, I hope it's not too bad though.

Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: > The loss of laziness in `y` is a bit unfortunate.

I think this is probably outweighed by the efficiencies gained from the greater `minNestingLevel` when we select `currentColumn`:

* We don't have to check `x` as far as with `lineIndent`.
* We can more often stick with `x` instead of switching to `y`.

Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Also note that `layoutPretty` is completely unaffected since it ignores the `minNestingLevel`:

https://github.com/quchen/prettyprinter/blob/4d51362d7ea8bca0fe9e7ffec2ccd8fcd0065c0d/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1644-L1647

Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: If `y` starts with one of the annotation constructors, we should probably look further for the first "proper" constructor…

**Comment by quchen** [comment]
Ha nice! At first I was concerned about your pattern matching on `y`, but then realized it’s a SimpleDoc, not a Doc, so matching is well-behaved and not just a hack that works in case the rest of the document is already normalized.

I agree the loss of laziness in `y` is unfortunate, but on the other hand selecting the nicer of two alternatives kind of has comparison between two things built in. I was actually surprised quite a few times that the library could away with looking only at the first alternative.

I’ll add another test to make sure `layoutPretty` isn’t affected after having another look at this at home this weekend, and make a release.

Thanks for all your work! I’m not sure how long it would have taken me to spot this one…

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs (hunk 1 above)
Comment (quchen) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: I went with the »annotations might mean something important even if they contain something unimportant« elsewhere (strip trailing whitespace), so I think ignoring annotations here is alright. What do you think?

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 2]
```diff
@@ -1785,7 +1785,9 @@ layoutWadlerLeijen
       | fits pWidth minNestingLevel availableWidth x = x
       | otherwise = y
       where
-        minNestingLevel = min lineIndent currentColumn
+        minNestingLevel = case y of
+            SLine _ _ -> lineIndent
```
Comment (quchen) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: I prefer `SLine{}` when ignoring all fields

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs (hunk 1 above)
Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: I'm actually not really familiar with how annotations work or how they are used.

But it seems to me that the result of `layoutWadlerLeijen` should not depend on the presence of annotations. Wouldn't the following property be desirable?

    layoutWadlerLeijen fp opts (unAnnotate doc) === unAnnotateS (layoutWadlerLeijen fp opts doc)

So I think it would be better to check what's behind the annotations.

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 3]
```diff
@@ -1785,7 +1794,16 @@ layoutWadlerLeijen
       | fits pWidth minNestingLevel availableWidth x = x
       | otherwise = y
       where
-        minNestingLevel = min lineIndent currentColumn
+        minNestingLevel =
+            -- See https://github.com/quchen/prettyprinter/issues/83.
+            if startsWithLine y
+                -- y might be a (more compact) hanging layout. Let's check x
+                -- thoroughly with the smaller lineIndent.
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: If we wanted to detect hanging layouts more precisely, we could also check that the indentation of the `SLine` is `< currentColumn`. But what we have right now is the slightly more conservative change.

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 4]
```diff
@@ -1785,7 +1794,16 @@ layoutWadlerLeijen
       | fits pWidth minNestingLevel availableWidth x = x
       | otherwise = y
       where
-        minNestingLevel = min lineIndent currentColumn
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Any idea why this was computed with `min` and didn't just return `lineIndent`?

Doesn't the invariant from above hold here?

    -- * current column >= current nesting level

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 5]
```diff
@@ -1785,7 +1794,16 @@ layoutWadlerLeijen
...
+        minNestingLevel =
+            -- See https://github.com/quchen/prettyprinter/issues/83.
+            if startsWithLine y
+                -- y might be a (more compact) hanging layout. Let's check x
+                -- thoroughly with the smaller lineIndent.
+                then lineIndent
+                -- y definitely isn't a hanging layout. Let's allow the first
+                -- line of x to be checked on its own and format it consistently
+                -- with subsequent lines with the same indentation.
+                else currentColumn
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: These are the general conditions under which `layoutSmart`, given a `Union x y`, will return `x` instead of `y` after this change:

* `y` doesn't start with a line break
* `lineIndent` must be `< currentColumn`
* a line of `x` (but not the first) with an indentation of `lineIndent < i <= currentColumn` is too wide.

Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: > * a line of `x` (but not the first) with an indentation of `lineIndent < i <= currentColumn` is too wide.

Actually that line must be "reachable" too. I.e. there's no other line with an indentation `<= lineIndent` before it.

**Comment by sjakobi** [comment]
@quchen Did you get a chance to look at this further?

Ideally I'd like to smoke-test this patch in projects that are likely to be impacted. Do you know any suitable projects?

The next best thing would IMHO be to just release this and wait for feedback. :)

**Comment by quchen** [comment]
Released 1.5. I don’t have that much time on my hands right now, sorry for the delays!

**Comment by sjakobi** [comment]
No worries. Thanks for the releases! :)
