### PR TITLE
WIP: Make Travis fail properly

### LINKED ISSUE #127: CI doesn't fail when tests fail
… at least for prettyprinter's doctests:

https://travis-ci.org/quchen/prettyprinter/jobs/640542206#L506

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #127.

### CODE REVIEW

**Comment by sjakobi** [comment]
Finally! :(

Tests with LTS-12 are failing already during the build, because `forAllShow` is out of scope: It was introduced in QC-2.12, but LTS-12.26 uses v2.11.3…

File: prettyprinter/test/Testsuite/Main.hs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 {-# LANGUAGE CPP               #-}
 {-# LANGUAGE OverloadedStrings #-}
-{-# OPTIONS_GHC -Wno-orphans   #-}
+{-# OPTIONS_GHC -fno-warn-orphans   #-}
```
Comment (sjakobi) [inline prettyprinter/test/Testsuite/Main.hs]: I didn't originally want to include this here. But it allows building the tests with GHC 7.8 and 7.10…
