### PR TITLE
Explain the fix for #83 in a proper note, and possibly even improve the fix a bit

### LINKED ISSUE #111: The fix for #83 needs a proper note
…with examples.

Even I can't remember how this worked anymore! :(

https://github.com/quchen/prettyprinter/blob/7d2225bc96425bd8f8a90cdd62063e37cec6a2ef/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1797-L1810

### PR DESCRIPTION
**Pull request by sjakobi**
Closes #111.

### CODE REVIEW

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 1]
```diff
@@ -1812,15 +1804,19 @@ layoutWadlerLeijen
...
-                    -- with subsequent lines with the same indentation.
-                    else currentColumn
+                -- See the Note
+                -- [Choosing the right minNestingLevel for consistent smart layouts]
+                case y of
+                    SLine i _ ->
+                        -- y could be a (less wide) hanging layout. If so, let's
+                        -- check x a bit more thoroughly so we don't miss a potentially
+                        -- better fitting y.
+                        min i currentColumn
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Possibly safer in case of an unexpectedly low `i`?

```suggestion
                        max lineIndent (min i currentColumn)
```

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 2]
```diff
@@ -1812,15 +1804,19 @@ layoutWadlerLeijen
...
-                    -- thoroughly with the smaller lineIndent.
-                    then lineIndent
-                    -- y definitely isn't a hanging layout. Let's allow the first
-                    -- line of x to be checked on its own and format it consistently
-                    -- with subsequent lines with the same indentation.
-                    else currentColumn
+                -- See the Note
+                -- [Choosing the right minNestingLevel for consistent smart layouts]
+                case y of
+                    SLine i _ ->
```
Comment (sjakobi) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Note that I don't try to look behind annotations anymore, mostly because it seemed unlikely to be useful. `dhall` doesn't need it in any case.

**Comment by sjakobi** [comment]
The documents that I would expect to profit from this way of computing `minNestingLevel` would look somewhat like this:

```
bla: A
  B
```

with an alternative hanging layout

```
bla:
  A
  B
```

Previously, to decide between these two layouts, we would also check `B` – `minNestingLevel` was the `lineIndent` of the first line: 0. With this change, `minNestingLevel` will be 2, which is the same as `B`'s indentation level, so we'll stop before checking `B`.

Admittedly I don't think that layouts like that are very widespread…

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs (hunk 1 above)
Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: I'd rather get a bug report. ;)

**Comment by sjakobi** [comment]
@quchen, @1Jajen1 Could you possibly review and suggest any possible improvements to the Note?

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs (hunk 2 above)
Comment (quchen) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: I think you definitely should look behind annotations! Dhall is just one application of Prettyprinter, and the design of the latter should not be simplified because a revdep does not need it. Performance-wise it’s not an issue anyway (I wouldn’t be surprised if the check for `Ann` would be free here, actually).

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs [hunk 3]
```diff
@@ -1846,20 +1842,117 @@ layoutWadlerLeijen
...
+1. We group a Doc containing a Line, producing a (Union x y) where
+   x contains Fail.
+
+2. In best, any Unions are handled recursively, rejecting any
+   alternatives that would result in SFail.
+
+So once a SimpleDocStream reaches selectNicer, any SFail in it must
+appear before the first linebreak – any other SFail would have been
+detected and rejected in a previous iteration.
+-}
```
Comment (quchen) [inline prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Sounds good. A bit long, but probably apt for explaining this relatively special case.

File: prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs (hunk 2 above)
Comment (sjakobi) [reply prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs]: Fixed.
